# Formul = Aylık kazanç + kira geliri - kira - mutfak masrafı - giyecek masrafı - yakıt - eğlence - diğer masraflar

print("Aylık ne kadar kazancım var ? ")
aylıkKazanc = input("Aylık maaşınız (tüm aile bireyleri): ")
kiraGeliri = input("Aylık varsa kira geliriniz yoksa '0' sayısını giriniz: ")
kira = input("Eviniz kiralıksa kira değerini giriniz, kiralık değilse '0' sayısını giriniz: ")
mutfakMasrafı = input("Aylık mutfak masrafınız: ")
giyecekMasrafı = input("Aylık kiyafet harcamanız: ")
yakıtMasrafı = input("Aylık yakıt masrafınız: ")
eglenceMasrafı = input("Aylık eglence masrafınız: ")
vergi = input("Varsa arabanızın vergisini girin yoksa '0' sayısını giriniz: ")
evVergi = input("Varsa evinizin vergisini giriniz yoksa '0' sayısını giriniz: ")
elektirikFatura = input("Aylık elektirik faturanız: ")
dogalgazFatura = input("Aylık doğalgaz faturanız: ")
telefonFatura = input("Aylık telefon faturanız: ")
suFatura = input("Aylık su faturanız: ")
krediBorcu = input("Aylık kredi borcuna ödediğiniz para: ")
formul = (float(aylıkKazanc) + float(kiraGeliri)) - float(kira) - float(mutfakMasrafı) - float(giyecekMasrafı) - float(yakıtMasrafı) - float(eglenceMasrafı) - (float(vergi)/12) - (float(evVergi)/12) - float(elektirikFatura) - float(krediBorcu) - float(dogalgazFatura) - float(telefonFatura) - float(suFatura)
yıllıkFormul = ((float(aylıkKazanc)*12) + (float(kiraGeliri)*12)) - (float(kira)*12) - (float(mutfakMasrafı)*12) - (float(giyecekMasrafı)*12) - (float(yakıtMasrafı)*12) - (float(eglenceMasrafı)*12) - float(vergi) - float(evVergi) - (float(elektirikFatura)*12) - (float(krediBorcu)*12) - (float(dogalgazFatura)*12) - (float(telefonFatura)*12) - (float(suFatura)*12)
print("yıllık", int(yıllıkFormul), "TL artan paranız var.")
print("aylık", int(formul), "TL artan paranız var.")
cıkma = input("Çıkmak için herhangi bir tuşa basınız: ")